# -*- coding: utf-8 -*-
"""FIGURAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecx_Cj9zqZ2RYY8MtPoCKYCf51dnPftD

PROGRAMA \ HECHO POR Itzel Rios Zavala
Figuras geometricas
triangulo, cuadrado, rectangulo
"""

class Figuras():
  def __init__(self, base, altura):
    self.base = base
    self.altura = altura
  def op(self):
    print("Elija una figura: ")
    print("1. Circulo")
    print("2. Trapecio")
    print("3. Rectangulo")
    op = int(input("Ingrese su opcion: "))
    return (op)
  def circulo (radio):
    a =3.1416 * radio**2
    return a
  def trapecio (b1,b2,a):
    return (b1+b2)*a/2
  def rectangulo (self):
    return self.base * self.altura
op = Figuras(0,0).op()
if op == 1:
#circulo
  circulo_a=int(input("Ingresa el radio: "))
  circulo= Figuras.circulo(circulo_a)
  print("Area de circulo", circulo)
elif op == 2:
#trapecio \ base1 + base 2 * altura / 2
  base_c=int(input("Ingresa la base 1: "))
  base_c2=int(input("Ingresa la base 2: "))
  altura_c=int(input("Ingresa la altura"))
  trapecio = Figuras.trapecio(base_c, base_c2, altura_c)
  print("Area de trapecio", trapecio)
elif op == 3:
#rectangulo
  base_r=int(input("Ingresa la base de rectangulo: "))
  altura_r=int(input("Ingresa la altura de rectangulo: "))
  rectangulo= Figuras(base_r, altura_r)
  print("Area de rectangulo", rectangulo.rectangulo())