# -*- coding: utf-8 -*-
"""holamundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ItzelRZ/0d7d65bc33bae2a0a913564fe7db42a5/holamundo.ipynb
"""

print("Hola mundo")

"""Mi primer programa | Hecho por Itzel Rios Zavala 06/02/25"""