# -*- coding: utf-8 -*-
"""saludo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kj_-cT2H9DVSfxjHDsIjuQ6GePJX3jHJ

Programa |hecho por Itzel Rios Zavala | 06/02/25
"""

class Saludo:
  def __init__(self):
    self.nombre = "itzel"
  def hola(self):
    print("Hola",self.nombre)
x=Saludo()
x.hola()

x=Saludo()
x.hola()