# -*- coding: utf-8 -*-
"""suma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_m7b5EqyONljn_owDczDnjX7DSsGwXd

Programa 3 | Hecho por Itzel Rios Zavla | 06/02/25
"""

class Suma:
  def __init__(self,num1,num2):
    self.num1=num1
    self.num2=num2
  def resultado(self):
    res=self.num1 + self.num2
    print(f"resultado = {res}")
y=Suma(5,8)
y.resultado()

y=Suma(5,8)
y.resultado()

"""Variante 2 pidiendo valores"""

class Suma:
  def __init__(self):
    self.num1=int(input("ingrese el primer numero: "))
    self.num2=int(input("ingrese el segundo numero: "))
  def resultado(self):
    res=self.num1 + self.num2
    print(f"Suma: {self.num1} + {self.num2} = {res}")
  def multiplicacion(self):
    multiplicacion=self.num1 * self.num2
    print(f"Multiplicacion: {self.num1} * {self.num2} = {multiplicacion}")
  def division(self):
    division=self.num1 / self.num2
    print(f"Division: {self.num1} / {self.num2} = {division}")

y=Suma()
y.resultado()
y.multiplicacion()
y.division()