# -*- coding: utf-8 -*-
"""SUMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1iWGRHWUqJNud3PiTv1m1FyJhyRh1Am

programa \ programa hecho por itzel rios zavala
"""

class Operaciones():
  def __init__(self,a,b):
    self.a=a
    self.b=b
  def Suma(self,v1,v2):
    self.res=self.a+self.b
    return (self.res)
v1=int(input("Dame valor 1: "))
v2=int(input("Dame valor 1: "))
obj=Operaciones(v1,v2)
r=obj.Suma(v1,v2)
print("la suma de los valores es: ",r)